### ISSUE TITLE
Elements in Navbar not in line

### ISSUE THREAD

**Issue by Sourav61** [IIITKalyaniFOSC/MediCare-Prime#32]
**Describe the bug**
Elements of the Navbar are not in line as Breast Cancer is appearing in next line which makes it look like a bug.

**To Reproduce**
1. Go to 'Heroku Deployed Model'
2. Click on 'https://medicare-prime.herokuapp.com/'
3. See error

**Expected behavior**
All elements in Navbar should be in same line.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/70853906/123903007-83367d80-d98b-11eb-817b-588a1a62bdcb.JPG)

**Comment by Sourav61** [comment]
@akshitadixit mam, Can you pls assign me this issue!!

**Comment by akshitadixit** [comment]
@Sourav61 drop the mam, yes asigned.

**Comment by Sourav61** [comment]
Should i create a PR now or tomorrow as Program officially starts from 1st July i.e. tomorrow @akshitadixit ?

**Comment by akshitadixit** [comment]
I believe you should wait for tomorrow.

**Comment by Sourav61** [comment]
okk thanks @akshitadixit

**Comment by akshitadixit** [comment]
Hey @Sourav61 I just saw an update that says the program starts from 10th July

**Comment by Sourav61** [comment]
okk so should i create a PR now or on 10th @akshitadixit ??

**Comment by akshitadixit** [comment]
I have raised a query with the core team will let you know

**Comment by Sourav61** [comment]
okk thanks alot @akshitadixit

**Comment by Sourav61** [comment]
@akshitadixit The actual issue occurs when we open model deployed on Heroku via https://medicare-prime.herokuapp.com/.
As when i opened it on my local it's working absolutely fine as you can see below!!

![Capture](https://user-images.githubusercontent.com/70853906/125185271-983fc600-e241-11eb-8eb5-5bfb6ed165ff.JPG)
![Capture1](https://user-images.githubusercontent.com/70853906/125185275-9d047a00-e241-11eb-891b-c558b666d15e.JPG)

**Comment by Sourav61** [comment]
@akshitadixit https://github.com/IIITKalyaniFOSC/MediCare-Prime/issues/32#issuecomment-877750559 please see to this as well!!

**Comment by akshitadixit** [comment]
> @akshitadixit The actual issue occurs when we open model deployed on Heroku via https://medicare-prime.herokuapp.com/.
> As when i opened it on my local it's working absolutely fine as you can see below!!

You just pointed out a bug even we didn't notice. Thanks. You can go ahead and create a separate issue giving reference to this one so someone could come up and fix this.

**Comment by Sourav61** [comment]
@akshitadixit Is it possible that someone(contributor) could make changes to deployed model as once you push your updated code on Heroku, everything will work fine?

**Comment by Sourav61** [comment]
@akshitadixit pls close this issue as it is already resolved, i guess!!
