### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by akshitadixit** [IIITKalyaniFOSC/MediCare-Prime#34]
**Issue**
A clean and organised documentation of the project should be hosted on the gh-pages branch.

**Required**
- [ ] About the project
- [ ] Tech stack used
- [ ] Dependencies
- [ ] Explaining the project structure
- [ ] How to set up the project locally
- [ ] Deployment info

**Additional context**
Completing all checkpoints in a single PR isn't necessary.
[Link](https://iiitkalyanifosc.github.io/MediCare-Prime/)

**Comment by Sakalya100** [comment]
Can I work on this issue?

**Comment by akshitadixit** [comment]
Sure @Sakalya100 :)

**Comment by Sakalya100** [comment]
@akshitadixit I have to make a readme file for this project right and the branch should be gh-pages?

**Comment by akshitadixit** [comment]
No @Sakalya100 you have to use the gh-pages branch and use the existing index.md file to add in one or more of the points mentioned above. Please visit the link given above to view the gh-pages deployment. For any assisstance, let me know.

**Comment by Sakalya100** [comment]
@akshitadixit Okay mam I  will try to do it.

**Comment by Sakalya100** [comment]
@akshitadixit mam I am unable to find the index.md file in the codebase which you told me to use. Can you please tell me where to find index.md file

**Comment by akshitadixit** [comment]
Drop the mam. 

The following commands could be of help:
* `git switch gh-pages` to switch to the github pages branch. When you do this, you should see index.md
* `git switch main` to switch back to main branch

If you do not fully understand this, drop a text in the #medicare channel on slack.

**Comment by Sakalya100** [comment]
Ok sure. I will try and in case of doubt I will drop a text
