### ISSUE TITLE
Parkinson's Disease Prediction

### ISSUE THREAD

**Issue by Akash20x** [IIITKalyaniFOSC/MediCare-Prime#36]
I want to add model of Parkinson's Disease Prediction and also add its prediction function in flask and html file. 

@akshitadixit Please assign me this issue.

**Comment by akshitadixit** [comment]
Sure :) are you under devincept or lgmsoc?

**Comment by Akash20x** [comment]
> Sure :) are you under devincept or lgmsoc?

I am in both program, but I want to solve this in DevIncept program

**Comment by akshitadixit** [comment]
Sure!

**Comment by harshita9621** [comment]
@akshitadixit Can I work on this issue under devincept'21.

**Comment by akshitadixit** [comment]
@Akash20x are you still on it or do we assign it to @harshita9621 ?

**Comment by Akash20x** [comment]
@akshitadixit I am working on it and I will send pull request on 10th July

**Comment by Akash20x** [comment]
@akshitadixit Please check my pull request
