### ISSUE TITLE
Footer not in Proper place and github link not working

### ISSUE THREAD

**Issue by Sourav61** [IIITKalyaniFOSC/MediCare-Prime#37]
**Describe the bug**

1. Footer is not lying at the bottom in Homepage and also when redirected to Malaria page same issue is occuring.
2. Github Link is not working when we click on Github icon on any page as name was changed from FOSC-IIIT-Kalyani to IIITKalyaniFOSC.

**To Reproduce**
1. Go to 'Home Page/ Malaria Page'
3. Scroll down to 'see the Footer'

**Expected behavior**
Footer should always lie at the bottom of the page and Github link should also be working to make it easier to view the source code.

**Screenshots**
![Capture2](https://user-images.githubusercontent.com/70853906/124234293-78b5e880-db31-11eb-8db7-73869495f54a.JPG)
![Capture3](https://user-images.githubusercontent.com/70853906/124234303-7a7fac00-db31-11eb-9486-d7f8d7a41e8f.JPG)
![Capture1](https://user-images.githubusercontent.com/70853906/124234305-7b184280-db31-11eb-8069-cd7da428c1d3.JPG)

- [ ] To place Footer in proper position
- [ ] To make the Github Link Working

**Comment by Sourav61** [comment]
@akshitadixit please assign me this issue!!

**Comment by akshitadixit** [comment]
@Sourav61 thanks for reporting the bug. Assigned.
