### ISSUE TITLE
Heart-Disease webpage

### ISSUE THREAD

**Issue by ParagD25** [IIITKalyaniFOSC/MediCare-Prime#38]
Heart-Disease webpage **does not** contain Header and Footer

![bug](https://user-images.githubusercontent.com/77889567/124364273-00991100-dc5e-11eb-85e4-1431e8c9c618.png)

**Comment by ParagD25** [comment]
assign this issue to me

**Comment by akshitadixit** [comment]
@ParagD25 assigned :)

**Comment by ParagD25** [comment]
I'm lgm-soc participant.
