### ISSUE TITLE
Two same diseases in Header

### ISSUE THREAD

**Issue by ParagD25** [IIITKalyaniFOSC/MediCare-Prime#46]
There are 2 occurrences of same disease 'Diabetes'  in Header

![TITLE](https://user-images.githubusercontent.com/77889567/124473341-d3af4000-ddbc-11eb-85ff-9733f5849764.png)

**Comment by ParagD25** [comment]
Can you assign this issue to me?

**Comment by akshitadixit** [comment]
Hey @ParagD25 actually the issue has been solved by a maintainer. You will see the changes when a push to deployment is made by us. Anyway thanks for your time :)
