### ISSUE TITLE
To make title bar dynamic.

### ISSUE THREAD

**Issue by ParagD25** [IIITKalyaniFOSC/MediCare-Prime#48]
Can I add a feature that would change title bar's name according to the webpage visited?

**Comment by akshitadixit** [comment]
Yea that'll be cool. However we recently closed #47 and will be pushing those changes to deployment by the end of the day. A bit of work is still left.

I'll assign you the issue but please start working on it only when I inform you.

**Comment by ParagD25** [comment]
ok, no problem

**Comment by ParagD25** [comment]
Hey @akshitadixit, can I start working on this now?

**Comment by akshitadixit** [comment]
@ParagD25 I believe contributors are asked to make PRs only after 10th, please confirm the same from slack.

**Comment by akshitadixit** [comment]
Hey @ParagD25 could you please reach out to me on slack? I have a better issue to discuss with you.

**Comment by ParagD25** [comment]
Ya Sure!!
