### ISSUE TITLE
Thyroid Disease Prediction

### ISSUE THREAD

**Issue by Akash20x** [IIITKalyaniFOSC/MediCare-Prime#58]
I want to add model of Thyroid Disease Prediction and also add its prediction function in flask and html file.

@akshitadixit Please assign me this issue as a part of devincept'21

**Comment by harshita9621** [comment]
@akshitadixit Can I work on this.

**Comment by Akash20x** [comment]
> @akshitadixit Can I work on this.

@harshita9621 I already asked to assign this issue to me. So please choose another issue.

**Comment by akshitadixit** [comment]
@Akash20x please have a look at my comment in #60 

Having said that, I'd like you both to team up for this and solve this collectively. You can make PR's contributing your part of the code.

**Comment by Akash20x** [comment]
@akshitadixit Please check my pull request
