### ISSUE TITLE
Add a Contributors Section

### ISSUE THREAD

**Issue by Prakash-Haldar** [IIITKalyaniFOSC/MediCare-Prime#60]
Hey I want to add a contributors section in this . which shows the People who contribute to this project
Assign this me as **DCP'21'**

**Comment by swathi-469** [comment]
I would like to work on this issue as part of LGM-SOC21

**Comment by Prakash-Haldar** [comment]
> I would like to work on this issue as part of LGM-SOC21

Make your own issue dude

**Comment by Prakash-Haldar** [comment]
@akshitadixit

**Comment by akshitadixit** [comment]
@Prakash-Haldar firstly, thank you for creating the issue. Sure will assign it to you. Secondly, I'd like you to delete your comment to @swathi-469 . You need to be respectful to any and everyone. Open source is no competition, rather it is about collaboration and working together. Many a times maintainers assign multiple people to work on the same issue so they have to team up. Nobody would want to talk to their teammates that way.

**Comment by Prakash-Haldar** [comment]
Yes , you are absolutely right @akshitadixit. even I am also a Beginner& know the problems which we face at earlier period.
@swathi-469" I am just Suggesting you to make your own issue". My attention was not wrong. But If you get hurt from words I am really apologies for That.

**Comment by akshitadixit** [comment]
Thank you for the apology and for understanding. Just be a little soft next time :)

**Comment by swathi-469** [comment]
Yeah, no problem ..I am also a beginner so don't know some rules and regulations that's why this happened. I am really sorry about that.

**Comment by Prakash-Haldar** [comment]
@akshitadixit  I have created The Pull Request. Please So To It
