### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by william-monroy** [IIITKalyaniFOSC/MediCare-Prime#64]
## **Description**
Fix responsive design for horizontal mobile devices and devices with 290 or less width.

## **Screenshots**
![responsive_medicare_horizontal](https://user-images.githubusercontent.com/58092741/125578676-7778308c-21e8-47d2-a04b-6c14ced377a6.png)
![responsive_medicare_vertical](https://user-images.githubusercontent.com/58092741/125578695-3ff953db-c7d0-42fb-b828-5d073fdf8d1f.png)

## **Device:**
 - OS: Windows
 - Browser Chrominum

## **Additional context**
Some elements are not aligned correctly.

**Comment by akshitadixit** [comment]
@william-monroy where'd you get this code from? I'm pretty sure the [deployment](https://medicare-prime.herokuapp.com/) look like this.

**Comment by william-monroy** [comment]
@akshitadixit from https://github.com/IIITKalyaniFOSC/MediCare-Prime/tree/main/UI

**Comment by akshitadixit** [comment]
@william-monroy  that was just a temporary ui, it isn't a part of the codebase anymore.

**Comment by william-monroy** [comment]
@akshitadixit Thanks for the clarification, I have some ideas to improve the UI of the page that you showed me, can you tell me how I find it?

**Comment by akshitadixit** [comment]
You can collaborate with @ParagD25 for the same.
