### ISSUE TITLE
Breast Cancer Wisconsin (Diagnostic) Data Set

### ISSUE THREAD

**Issue by harshita9621** [IIITKalyaniFOSC/MediCare-Prime#65]
# About 

- Predict whether the cancer is benign or malignant.

Dataset: https://www.kaggle.com/uciml/breast-cancer-wisconsin-data

Can I work on this issue.

**Comment by dilroseR** [comment]
can i try this issue?

**Comment by akshitadixit** [comment]
@harshita9621 the breast cancer model has already been added in the repo.
