### ISSUE TITLE
Chronic disease

### ISSUE THREAD

**Issue by soma2000-lang** [IIITKalyaniFOSC/MediCare-Prime#67]
@akshitadixit mam
I would like to add a model on Chronic disease  and do  Exploratory Data Analysis on that

Please Assign me this Issue.

**Comment by akshitadixit** [comment]
@soma2000-lang sure, assigned. Let me know which open source program you coming from. ALso please skip ma'am.

**Comment by soma2000-lang** [comment]
yes ,I am from LGM-SoC-21
