### ISSUE TITLE
Adding logo in title bar of the Website

### ISSUE THREAD

**Issue by Sourav61** [IIITKalyaniFOSC/MediCare-Prime#69]
**Describe the bug**
When you open website, there is no logo which does not make it look like a complete website.

**Expected behavior**
A logo is a necessity for any website, so adding logo would be a wise thing to do.

**Screenshots**
![Capture10](https://user-images.githubusercontent.com/70853906/126043704-5a3b2cab-ad76-4c09-b292-ae8a5f0edfec.JPG)

**Comment by Sourav61** [comment]
@akshitadixit pls assign me this issue!!

**Comment by Sourav61** [comment]
Have a look at the logo here!!

https://thumbs.dreamstime.com/b/health-care-logo-illustration-art-isolated-background-42265698.jpg

@akshitadixit If you have any other suggestion for the logos, then please let me know!!

**Comment by akshitadixit** [comment]
@Sourav61 kindly have a look at the readme for the logo

**Comment by Sourav61** [comment]
https://github.com/IIITKalyaniFOSC/MediCare-Prime/blob/main/static/images/MEDICARE.gif

Is this the logo that you are referring to @akshitadixit ??

**Comment by akshitadixit** [comment]
Yes @Sourav61

**Comment by Sourav61** [comment]
@akshitadixit As you can see in image below, due to being of small size, it doesn't appear to be anything related to Medical Science, instead appears to be a computer.

![Capture9](https://user-images.githubusercontent.com/70853906/126117505-b33bcc74-4409-455e-984e-dbe477c5869a.JPG)

So in my opinion we shoould look for other options which will be best suited in this situation!!

**Comment by Sourav61** [comment]
@akshitadixit Should i make a pull request applying logo given in link below?

https://github.com/IIITKalyaniFOSC/MediCare-Prime/blob/main/static/images/MEDICARE.png

**Comment by Sourav61** [comment]
@akshitadixit pls reply!!

**Comment by akshitadixit** [comment]
@Sourav61 sure go ahead. Sorry was involved elsewhere.
