### ISSUE TITLE
Push changes to deployment

### ISSUE THREAD

**Issue by akshitadixit** [IIITKalyaniFOSC/MediCare-Prime#72]
Since the last deployment, many changes have been introduced. Need to push the code to deployment branch.

**Comment by Sourav61** [comment]
@akshitadixit , I would like to work on this issue!!

**Comment by akshitadixit** [comment]
@Sourav61 sorry but this issue needs to be done by me, this isn't available for contributions

**Comment by Sourav61** [comment]
okk @akshitadixit
